version: 2
orbs:
  codecov: codecov/codecov@1.0.2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.4
    steps:
      - checkout
      - run: pip install coverage --user
      - run:
          name: Run Tests
          command: |
            $HOME/.local/bin/coverage run -m unittest tests/tests.py
            $HOME/.local/bin/coverage report
            $HOME/.local/bin/coverage html
      - store_artifacts:
          path: htmlcov
      - codecov/upload:
          file: htmlcov
workflows:
  version: 2
  workflow:
    jobs:
      - build